name: Benchmark

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src-tauri/benches/**"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo bench
        working-directory: src-tauri
